project:
  type: website
  output-dir: docs

website:
  title: "Subramaniam Subramanian Murugesan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://scholar.google.co.uk/citations?user=0vldbTgAAAAJ&hl=en
        text: Google Scholar
      - href: https://www.researchgate.net/profile/Subramaniam-Subramanian-Murugesan
        text: ResearchGate
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    includes:
      in-header: |
        <link rel='shortcut icon' type='image/x-icon' href='/images/favicon.ico'

execute:
  enabled: true
  jupyter: true
  kernel: python3
